### ISSUE TITLE
can u write more details about how to run it?

### ISSUE THREAD

**Issue by PeopleComeAndGo** [sshh12/Financial-News-Indexing#2]
after pip install requirements.txt
python scripts\watch.py   got lots of errors.

thanks.

**Comment by sshh12** [comment]
Hey! I'm still actively modifying how this works so I've procrastinated writing any docs that might change in the near future.

Try with config.yaml set to 
```yaml
watch:
  news:
    delay: 10
    sources: [accesswire, alphastocknews, barrons, benzinga, businessinsider, businesswire,
      cnn, federalreserve, financialtimes, fitch, forbes, globenewswire, marketexclusive,
      marketwatch, miningnewsfeed, moodys, pharmiweb, prnewswire, reuters, rtt, seekingalpha,
      stat, stocktwits, streetinsider, thestreet, usbls, yahoo]
```
and lmk what the script outputs.
